services:
  backend:
    build: ./Backend
    container_name: Backciber
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - ciber3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/notas"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



  frontend:
    build: ./Frontend
    container_name: Frontciber
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./Frontend:/app
    networks:
      - ciber3

networks:
  ciber3:
    driver: bridge