services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./Backend
          target: /app


  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app