services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    restart: always